# Generated by Django 4.1.1 on 2022-10-12 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_takepic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TakePic',
        ),
        migrations.AlterField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
