# Generated by Django 4.1.1 on 2022-10-12 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognize_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
